development:
      host: localhost
      adapter: mysql
      database: harry_field_dev
      port: 3306
      username: root
      password: hetalksinme2

test: &test
      host: localhost
      adapter: mysql
      database: harry_field_test
      port: 3306
      username: root
      password: hetalksinme2

production:
      host: localhost
      adapter: mysql
      database: harry_field_prod
      port: 3306
      username: root
      password: hetalksinme2
cucumber:
  <<: *test