development:
      host: localhost
      adapter: mysql
      database: dev_db_erp
      port: 3306
      username: root
      password: Mrsayinsansa@123

test: &test
      host: localhost
      adapter: mysql
      database: test_db_erp
      port: 3306
      username: root
      password: Mrsayinsansa@123

production:
      host: localhost
      adapter: mysql
      database: harry_field
      port: 3306
      username: root
      password: Mrsayinsansa@123
cucumber:
  <<: *test